# Generated by Django 4.2 on 2024-12-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('division_id', models.IntegerField(blank=True, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('subdistrict_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('application_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=510)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(max_length=255)),
                ('birth_country', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_division_id', models.IntegerField()),
                ('birth_district_id', models.IntegerField()),
                ('birth_subdistrict_id', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('father_name', models.CharField(max_length=255)),
                ('father_nid', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_nid', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('mother', 'mother'), ('father', 'father'), ('brother', 'brother'), ('sister', 'sister')], max_length=10)),
                ('division_id', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('subdistrict_id', models.IntegerField()),
                ('healthcare_id', models.IntegerField()),
                ('application_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='BabyReg',
            fields=[
                ('reg_no', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birth', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_nid', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_nid', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('vaccine_centre', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'baby_reg',
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_nid', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_nid', models.CharField(blank=True, max_length=255, null=True)),
                ('present_division', models.CharField(blank=True, max_length=255, null=True)),
                ('present_district', models.CharField(blank=True, max_length=255, null=True)),
                ('present_upazila', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_division', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_upazila', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'citizen',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'divisions',
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=100)),
                ('vaccine_id', models.IntegerField()),
                ('dose_number', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(default='Scheduled', max_length=255)),
                ('healthcare_id', models.IntegerField()),
                ('volunteer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaccination_schedule',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('vaccine_code', models.CharField(max_length=100, unique=True)),
                ('doses', models.IntegerField()),
                ('time_intervals', models.JSONField()),
                ('manufactured_country', models.CharField(blank=True, max_length=255, null=True)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vaccine',
            },
        ),
        migrations.CreateModel(
            name='VaccineStatus',
            fields=[
                ('application_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vaccine_status',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('healthcare', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('subdistrict_id', models.IntegerField()),
                ('healthcare_id', models.IntegerField()),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.district')),
            ],
            options={
                'db_table': 'subdistricts',
            },
        ),
        migrations.CreateModel(
            name='Healthcare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.subdistrict')),
            ],
            options={
                'db_table': 'healthcare',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.division'),
        ),
    ]
